### PR TITLE
backends: add egl backend

### PR DESCRIPTION
**Pull request by yshui**
This needs the EGL_KHR_image_pixmap and the GL_EXT_EGL_image_storage
extensions, which unfortunately aren't available on NVIDIA cards.

Don't add documentation for these, for now.

Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>

### CODE REVIEW

**Comment by yshui** [comment]
I was expecting to get bugs, driver problems, and a ton of debugging. But to my surprise everything just works on the first try.

Maybe I should have tried this sooner.

**Comment by yshui** [comment]
I will merge this with the added warning about it still being experimental.

**Comment by yshui** [comment]
Hmm, man pages failed to build but I didn't touch them. I will ignore those failures.

**Comment by vincentbernat** [comment]
How to choose between EGL and GLX? Should people favor EGL if it works?

**Comment by yshui** [comment]
@vincentbernat honest answer: I am not sure. I believe EGL uses newer code path in X and mesa, so it could work better. But if you already have no problem with GLX then it's probably not beneficial.

**Pull request merged**
