### PR TITLE
Convert XFixes usage to xcb

### PR DESCRIPTION
**Pull request by psychon**
Hi,

sorry for the messy commits yesterday. Hopefully, this one is easier to look at. I tried to create lots of small commits. I'm a bit unhappy with the commit that handles XFixesFetchRegion, but the rest should be quite easy to look at.

Depending on how fast you are, I'll update this with some commits handling XComposite because that seems quite easy to do.

Cheers

### CODE REVIEW

**Comment by psychon** [comment]
Note that lots of code still uses Xlib definitions (e.g. `XserverRegions` or `CompositeRedirectManual`). I'll leave fixing that up for later. Currently, this should not cause any problems since the XIDs and constants are compatible.

**Comment by psychon** [comment]
Quick FYI: I won't be able to get rid of libXext. The DOUBLE-BUFFER extension (Xdbe) was never described in xcb/proto's XML format and thus was never added to libxcb. Supposedly it is deprecated, but I do not really know. I'd just leave this with using libXext (and if I didn't miss anything, this is the only remaining extension that compton uses).

**Comment by yshui** [comment]
Sorry, I am going to need to postpone this a bit because it's going clash with my pixman conversion.

**Comment by yshui** [comment]
Sorry, I should've communicated better. Since I am converting XfixesRegion to pixman, you don't need to port those calls.

**Comment by yshui** [comment]
> The DOUBLE-BUFFER extension (Xdbe) was never described in xcb/proto's XML format and thus was never added to libxcb. 

I think it will probably be a good idea to remove xdbe.

**Comment by psychon** [comment]
Ah okay, then I will just leave this laying around and do a new PR for other stuff. No worries, in contrast to my first PR, this time I "did it right" and created small commits (sorry that I got this wrong the first time). That should also mean that this should be not too hard to rebase.

**Comment by yshui** [comment]
@psychon Thanks. I will close this.

**Pull request closed without merging**
