### PR TITLE
core: drop xcb-glx

### PR DESCRIPTION
**Pull request by absolutelynothelix**
it's only used for querying the x glx extension and it's error definitions. other than this, it has little to no use for us. see https://stackoverflow.com/q/41069032 for details.

### CODE REVIEW

**Comment by yshui** [comment]
i don't like that part of the X error handling depends on the backend. i also don't like you are using the backend to initialize part of `session_t`.

but i do like the removal of dependencies. do we really need to handle glx errors in `x.c`? are we not already doing it in the glx backend?

**Comment by absolutelynothelix** [comment]
> i also don't like you are using the backend to initialize part of `session_t`.

initially i wanted to replace the old xcb-style x glx extension querying in the `session_init` function with
```c
#ifdef CONFIG_OPENGL
	ps->glx_exists = glXQueryExtension(ps->dpy, &ps->glx_error, &ps->glx_event);
#endif
```
but ended up reverting to what we previously had (2372127c0f81b247945acf9075630a37bbcb5ae2). does my initial approach sound better?

> i don't like that part of the X error handling depends on the backend.

there is no "dependency". glx is an x extension just like the sync one which errors are handled below so i think it's fair to handle it's errors there.

> do we really need to handle glx errors in `x.c`? are we not already doing it in the glx backend?

i think that you're confusing glx errors with gl errors. gl errors are indeed handled in the `gl_common.c`. for glx errors, see my answer above. afaiu, unfortunately, there is no way to explicitly handle glx errors (e.g. in the xcb checked functions style).

**Comment by yshui** [comment]
> i think that you're confusing glx errors with gl errors. 

you are right. in that case i don't really see the point of removing xcb-glx.

**Comment by absolutelynothelix** [comment]
> i don't really see the point of removing xcb-glx

the point is that we're requiring it only to do things that could be done without it and it's very unlikely that we can make any other use of it.

**Comment by yshui** [comment]
we have it so we can have a healthy separation between the backend and the rest of picom. i don't like the increase in coupling caused by removing it. it's not that big of a dependency anyway.

**Comment by absolutelynothelix** [comment]
well, if my initial approach shown above doesn’t improve the situation feel free to close this pull request.

**Pull request closed without merging**
