### PR TITLE
[WIP] Remove the old backends

### PR DESCRIPTION
**Pull request by yshui**
Signed-off-by: Yuxuan Shui <yshuiv7@gmail.com>

### CODE REVIEW

**Comment by ggroucho** [comment]
Does this mean that compton will no longer be compatible with opengl 2?
The old glx backend is the best solution on my old hardware to remove tearing.
I have tried the xrender backend, but the performance is not as good.

**Comment by yshui** [comment]
@ggroucho xrender should be preferred on old hardware. Can you elaborate why do you think xrender is not performant?

Also, what is your hardware setup?

**Comment by ggroucho** [comment]
I am using compton on an laptop with a first gen core i5 (which is limited to opengl 2.1 unfortunately).

My most demanding use case should be playing 60fps videos with firefox or mpv on an external monitor while doing something else on the laptop.
With the old glx backend, it was almost flawless. But with the xrender backend it is jerky (or maybe I haven't found the correct settings? There also seem to be an issue with Xorg 1.20.5, unfortunately I have difficulties to test Xorg git).

**Comment by ggroucho** [comment]
Actually, there is also screen tearing with the old opengl backend on vNext.
I guess I will have to stick to v7, which is the best version of compton for my use.

**Comment by yshui** [comment]
@ggroucho there is no change made to the old backend since v7

**Comment by ggroucho** [comment]
@yshui I can reproduce it every time, going back and forth between compton-git and compton in Arch Linux with the same config file.

With compton-git, mpv is tearing when it is in full screen on one of the monitors (I have tried opengl and xv outputs). But I have no issues with v7, even when mpv is in full screen on both monitors.

**Comment by aruhier** [comment]
@ggroucho : are you sure you're using 7.0 and not 6.2? The 7.0 has been updated 13h ago in [community]

**Comment by ggroucho** [comment]
@aruhier Yes, it did my test with 7.0.

But I have managed to remove the tearing with vNext and the old opengl backend by adding mpv to the unredir-if-possible-exclude list.
Which actually makes sense, since I have the issue with no composition. I guess I was using a bug as a feature...

I will try to give xorg-server-git another go, to see if it solves my issues with the new xrender backend.

**Comment by aufkrawall** [comment]
@ggroucho modesetting driver of xorg has a bug with Intel which causes stutter in regular intervals in mpv (and possibly elsewhere). Thus xf86-video-intel should be used.
But xf86-video-intel vsync was broken with xorg-server 1.20.5, it will all hopefully be fine again with 1.20.6.

Long story short for the meantime: You need to compile xorg-server-git, install it and then recompile xf86-video-intel(-git) against that newly installed xorg-server-git. This works fine for me with Gemini Lake, no tearing or stutter with new experimental xrender backend + vsync.

**Comment by ggroucho** [comment]
@aufkrawall Thank you very much.

I have tried compton-git and the latest xorg-server-git with the Intel driver (SNA, with and without TearFree) and with modesetting:
- overall the performance is ok with one monitor
- but the old opengl backend is still better with two monitors

It is not bad, but I think I will stick to a version with the old opengl backend.
It is the best performance I can get from this old machine for my particular use.

**Comment by yshui** [comment]
@ggroucho Rendering with xrender is actually hardware accelerated and should have performance on par with opengl if blurring is not used (in fact, if you use the modesetting driver, xrender is actually using opengl behind the scene through glamor).

I feel bad that you are stuck with an older version of compton, but OTOH compton cannot support old hardware forever. I will see what I can do with the performance of the new xrender client, hopefully one day it will be good enough for you.

**Comment by ggroucho** [comment]
@yshui No worries. 
Thanks to you and to every one for the help.

**Comment by aufkrawall** [comment]
Just my two cents: Perhaps it wouldn't be a bad idea to wait with this until xorg 1.20.6 and xf86-video-amdgpu 19.1 are released, as they are important for new xrender backend vsync. Shouldn't take too long anymore.

**Comment by yshui** [comment]
@aufkrawall don't worry. this is more a WIP. there are still features missing from the new backends (e.g. `glx-fshader-win`) so this probably won't be merged anytime soon.

**Comment by yshui** [comment]
Yay we are finally free from the shackles of the old backends! :tada: :tada: 

a54adb62dad8c7c7466b082c492d5e62a5175881

**Pull request closed without merging**
