### PR TITLE
xrender: fix leak in deinit

### PR DESCRIPTION
**Pull request by absolutelynothelix**
fixes at least #960

i'm on fire today :sunglasses:

https://user-images.githubusercontent.com/52252283/209015581-dfaf8bd9-e148-4399-9522-bd4706a92253.mp4

### CODE REVIEW

**Comment by yshui** [comment]
:fire:

**Comment by yshui** [comment]
can you also add a `if (xd->back[i] != XCB_NONE)` for me?

**Comment by absolutelynothelix** [comment]
> can you also add a `if (xd->back[i] != XCB_NONE)` for me?

looking at the `backend_xrender_init` i believe it should look like this?
```c
        for (int i = 0; i < 3; i++) {
                if (xd->back[i] != XCB_NONE) {
                        xcb_render_free_picture(xd->base.c, xd->back[i]);
                }
                if (xd->back_pixmap[i] != XCB_NONE) {
                        xcb_free_pixmap(xd->base.c, xd->back_pixmap[i]);
                }
        }

```

**Comment by yshui** [comment]
yep!

**Comment by absolutelynothelix** [comment]
ah, give me a second to figure out how do i commit it properly

**Comment by absolutelynothelix** [comment]
done

**Comment by yshui** [comment]
thank you!

**Pull request merged**
