### PR TITLE
Animation part 6 extra: geometry trigger

### PR DESCRIPTION
**Pull request by yshui**

### CODE REVIEW

**Comment by yshui** [comment]
I believe this has everything now, even cross-fading between window contents.

**Comment by colonelpanic8** [comment]
hey, I believe there is still an issue with how the window-before properties are being populated.

Basically, as far as I can tell, we end up losing the context of where the previous position was, so the properties end up simply matching the current window always.

I actually have a very gross thing (that definitely is not something that can be merged) that does fix the issue here:

https://github.com/colonelpanic8/picom/blob/35fc591aca4de2721d784a9c3498498dd6f85adb/src/transition/script.h#L38

**Comment by colonelpanic8** [comment]
but yea, basically, I think we need to calculate the win_script_context once (when the animation is created) and continue to use that instead of recalculating it as the animation passes.

**Comment by colonelpanic8** [comment]
I'm happy to contribute a proper fix if you agree that this is the right way to do it.

Maybe there is a better place to store this pre calculated win_ctx (than https://github.com/colonelpanic8/picom/blob/35fc591aca4de2721d784a9c3498498dd6f85adb/src/transition/script.h#L38)?

**Comment by colonelpanic8** [comment]
may not be helpful but this is the animation I was using to test:

```
animations = ({
    triggers = ["geometry"];
    v-timing = {
	    curve = "cubic-bezier(0.17, 0.67, 0.68, 1.03)";
        end = 0;
        duration = 1.0;
        start = 1;
    };
    initial-x-offset = "window-x-before - window-x";
    initial-y-offset = "window-y-before - window-y";
    offset-x = "initial-x-offset * v-timing";
	offset-y = "initial-y-offset * v-timing";
} );
```

**Comment by yshui** [comment]
@colonelpanic8 `window-*-before` is never intended to be used this way. the intention has always been for them to reflect the current state of the window once the animation is started. for example, you cannot use them like this: `initial-x-offset = "window-x-before - window-x";`

**Comment by yshui** [comment]
but yeah, I should've made that clear in the documentation.

**Comment by colonelpanic8** [comment]
@yshui ...okay but I mean there is a need to do something like this if you want to animate a window from where it previously was, right?

**Comment by colonelpanic8** [comment]
I don't see what the purpose of window-x-before could even possibly be if it is not this.

**Comment by colonelpanic8** [comment]
also, I think you may be misunderstanding...

in the documentation it says:

```
  _c_, _window-y-before_, _window-width-before_, _window-height-before_:: The size and coordinates of the window before the animation is triggered. This is only meaningfully different from the normal window geometry variables for the _geometry_ trigger.
  ```
  
  it explicitly says BEFORE the animation is triggered.
  
  If this isn't how they're supposed to be used, can you actually describe a situation where window-x-before != window-x?

**Comment by yshui** [comment]
@colonelpanic8 

> it explicitly says BEFORE the animation is triggered.

It's a poor choice of words, I have updated it.

>  if you want to animate a window from where it previously was, right?

yes, so you use them in `start` and/or `end` values of a timing function. you can find examples in the presets: https://github.com/yshui/picom/blob/0585e3172d271914efa5e25fd0296b7d481f820b/data/animation_presets.conf#L166-L204

**Comment by colonelpanic8** [comment]
look at the example that I gave. Its just much easier to write things like that and its pretty surprising that its not possible.

Also, its not hard to just support allowing the definition of constants like this that you may not actually want to be part of a timing curve.

at the very least, if you dont want to allow this usage, it should then be an error to use them in defining a variable.

**Comment by yshui** [comment]
allowing this does not enable any new functionality. and i think the updated documentation should have made this behavior clear (let me know if you think it can still be improved).

this style of writing animations:

```
offset-x = "initial-x-offset * v-timing";
```

makes it difficult to smoothly interrupt an ongoing animations and start a different one. picom automatically adjusts offset and scale so the window doesn't "jump". if you use a generic variable `v-timing`, picom won't know how to deal with that.

for that reason, i don't think that's something picom should support.

on the other hand i also don't see a reason to prohibit it outright.

**Comment by yshui** [comment]
> makes it difficult to smoothly interrupt an on going animations

to expand on that, if `offset-x`, `offset-y`, etc. are all separate timing functions, picom can override their start values so animations are smooth. but picom can't do that if they are expressions.

**Pull request merged**
