### PR TITLE
fix a few memory leaks reported by valgrind

### PR DESCRIPTION
**Pull request by liskin**
(should probably be cherry-picked to stable as well)

### CODE REVIEW

**Comment by yshui** [comment]
@liskin Good catches!

This commit seems to include three independent memory leaks, could you split them up into individual commits? Remember to include a brief description of the leak in the commit message.

Thanks!

**Comment by liskin** [comment]
Sure, done!

**Comment by yshui** [comment]
Thanks a lot!

**Comment by yshui** [comment]
@liskin FYI, 7.4 is released with these fixes.

**Pull request merged**
